/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoursesSlugRouteImport } from './routes/_authenticated/courses.$slug'
import { Route as AuthenticatedLessonLessonIdRouteImport } from './routes/_authenticated/lesson.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoursesSlugRoute =
  AuthenticatedCoursesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedCoursesRoute,
  } as any)
const AuthenticatedLessonLessonIdRoute =
  AuthenticatedLessonLessonIdRouteImport.update({
    id: '/lesson/$lessonId',
    path: '/lesson/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/courses/$slug': typeof AuthenticatedCoursesSlugRoute
  '/lesson/$lessonId': typeof AuthenticatedLessonLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/courses/$slug': typeof AuthenticatedCoursesSlugRoute
  '/lesson/$lessonId': typeof AuthenticatedLessonLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/courses/$slug': typeof AuthenticatedCoursesSlugRoute
  '/_authenticated/lesson/$lessonId': typeof AuthenticatedLessonLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/courses'
    | '/dashboard'
    | '/courses/$slug'
    | '/lesson/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/courses'
    | '/dashboard'
    | '/courses/$slug'
    | '/lesson/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/courses'
    | '/_authenticated/dashboard'
    | '/_authenticated/courses/$slug'
    | '/_authenticated/lesson/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/$slug': {
      id: '/_authenticated/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof AuthenticatedCoursesSlugRouteImport
      parentRoute: typeof AuthenticatedCoursesRoute
    }
    '/_authenticated/lesson/$lessonId': {
      id: '/_authenticated/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof AuthenticatedLessonLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedCoursesRouteChildren {
  AuthenticatedCoursesSlugRoute: typeof AuthenticatedCoursesSlugRoute
}

const AuthenticatedCoursesRouteChildren: AuthenticatedCoursesRouteChildren = {
  AuthenticatedCoursesSlugRoute: AuthenticatedCoursesSlugRoute,
}

const AuthenticatedCoursesRouteWithChildren =
  AuthenticatedCoursesRoute._addFileChildren(AuthenticatedCoursesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLessonLessonIdRoute: typeof AuthenticatedLessonLessonIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCoursesRoute: AuthenticatedCoursesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLessonLessonIdRoute: AuthenticatedLessonLessonIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
